---
author_association: OWNER
created_at: '2025-08-17T12:26:29Z'
html_url: https://github.com/stellabo/daily_report/issues/27#issuecomment-3194354013
id: 3194354013
issue_url: https://api.github.com/repos/stellabo/daily_report/issues/27
node_id: IC_kwDOKDBFSs6-Zfld
performed_via_github_app: 
reactions:
  "+1": 0
  "-1": 0
  confused: 0
  eyes: 0
  heart: 0
  hooray: 0
  laugh: 0
  rocket: 0
  total_count: 0
  url: https://api.github.com/repos/stellabo/daily_report/issues/comments/3194354013/reactions
updated_at: '2025-08-17T12:40:28Z'
url: https://api.github.com/repos/stellabo/daily_report/issues/comments/3194354013
user:
  avatar_url: https://avatars.githubusercontent.com/u/46933816?v=4
  events_url: https://api.github.com/users/stellabo/events{/privacy}
  followers_url: https://api.github.com/users/stellabo/followers
  following_url: https://api.github.com/users/stellabo/following{/other_user}
  gists_url: https://api.github.com/users/stellabo/gists{/gist_id}
  gravatar_id: ''
  html_url: https://github.com/stellabo
  id: 46933816
  login: stellabo
  node_id: MDQ6VXNlcjQ2OTMzODE2
  organizations_url: https://api.github.com/users/stellabo/orgs
  received_events_url: https://api.github.com/users/stellabo/received_events
  repos_url: https://api.github.com/users/stellabo/repos
  site_admin: false
  starred_url: https://api.github.com/users/stellabo/starred{/owner}{/repo}
  subscriptions_url: https://api.github.com/users/stellabo/subscriptions
  type: User
  url: https://api.github.com/users/stellabo
  user_view_type: public

---
「エラー対応を自分でしないといけないのが厄介」と言った矢先、早速エラーが発生した。

![image](https://github.com/user-attachments/assets/59375181-eb78-434b-887b-5e2dc36cb6cc)

setup-node@v2 は廃止されたバージョンに依存しているため、現在はsetup-node@v4 にアップグレードされているらしく、
setup-node＠V2→setup-node@V4にすることで、エラーを解消することができた。